<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.example.TestSuite" tests="6" skipped="1" failures="1" errors="1" timestamp="2023-10-27T10:00:00" hostname="localhost" time="5.432">
    <properties/>
    <testcase name="successfulLoginTest" classname="com.example.auth.LoginTests" time="1.205"/>
    <testcase name="successfulDataFetch" classname="com.example.api.DataTests" time="2.510"/>
    <testcase name="invalidPasswordTest" classname="com.example.auth.LoginTests" time="0.850">
        <failure message="expected: <true> but was: <false>" type="org.opentest4j.AssertionFailedError">
            org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
            at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
            at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
            at com.example.auth.LoginTests.invalidPasswordTest(LoginTests.java:45)
        </failure>
    </testcase>
    <testcase name="apiTimeoutTest" classname="com.example.api.DataTests" time="0.500">
        <error message="java.net.SocketTimeoutException: connect timed out" type="java.net.SocketTimeoutException">
            java.net.SocketTimeoutException: connect timed out
            at java.net.PlainSocketImpl.socketConnect(Native Method)
            at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
            at com.example.api.DataTests.apiTimeoutTest(DataTests.java:30)
        </error>
    </testcase>
    <testcase name="paymentModuleTest" classname="com.example.billing.PaymentTests" time="0.367">
        <skipped/>
    </testcase>
    <testcase name="userProfileUpdateTest" classname="com.example.user.ProfileTests" time="0.001"/>
</testsuite>